/**
 * Realistic Mock Data for OceanShield AI Maritime Surveillance System
 * Region: Arabian Sea & Western Indian Ocean Maritime Shipping Corridor
 */

export const REGIONS = [
  { id: 'arabian-sea', name: 'Arabian Sea (Sector Alpha)', center: [19.2, 70.8], zoom: 7 },
  { id: 'strait-of-hormuz', name: 'Strait of Hormuz (Sector Bravo)', center: [26.4, 56.4], zoom: 8 },
  { id: 'persian-gulf', name: 'Persian Gulf (Sector Charlie)', center: [27.0, 51.5], zoom: 7 },
  { id: 'bay-of-bengal', name: 'Bay of Bengal (Sector Delta)', center: [15.5, 85.2], zoom: 6 },
];

export const DEMO_KPIS = {
  activeSpills: {
    value: 3,
    label: 'Active Oil Spills',
    change: '+1 in last 24h',
    trend: 'up',
    status: 'critical',
  },
  totalArea: {
    value: '42.8 km²',
    label: 'Total Detected Area',
    change: '+6.4 km² change',
    trend: 'up',
    status: 'warning',
  },
  trackedVessels: {
    value: 148,
    label: 'Tracked AIS Vessels',
    change: '94.2% transponder coverage',
    trend: 'neutral',
    status: 'normal',
  },
  candidateCorrelations: {
    value: 7,
    label: 'Candidate Correlations',
    change: '2 high-confidence matches',
    trend: 'up',
    status: 'warning',
  },
};

export const DEMO_SYSTEM_STATUS = {
  frontend: { name: 'Frontend Command Core', status: 'Operational', version: 'v1.0.0-PROD' },
  apiConnection: { name: 'Backend API Service', status: 'Not connected (Demo Mode)', code: 'STANDBY' },
  aiModel: { name: 'AI Detection Engine', status: 'Demo Mode (ResNet-UNet v2.4)', latency: '340ms (Simulated)' },
  aisFeed: { name: 'AIS Satellite Telemetry', status: 'Simulated Feed (5s interval)', rate: '142 msgs/min' },
  lastSync: new Date().toISOString(),
};

export const DEMO_INCIDENTS = [
  {
    id: 'OS-2026-089',
    timestamp: '2026-09-21T21:45:00Z',
    lat: 19.345,
    lng: 70.920,
    locationName: 'Arabian Sea - Mumbai High West Corridor',
    area: 14.8,
    perimeter: 18.2,
    confidence: 94,
    status: 'Active',
    satelliteSource: 'Sentinel-1B (SAR C-Band Interferometric Wide)',
    driftDirection: 'East-Northeast (065°)',
    driftSpeed: 1.4,
    description: 'High-backscatter signature indicative of mineral oil discharge observed across dense commercial shipping lane.',
    candidateVesselsCount: 3,
    timeline: [
      { time: '2026-09-21 21:45 UTC', title: 'Satellite Pass Acquisition', desc: 'Sentinel-1B SAR scene acquired over Sector Alpha.' },
      { time: '2026-09-21 21:58 UTC', title: 'Automated Dark-Spot Segmentation', desc: 'ResNet-UNet pipeline classified slick with 94% confidence.' },
      { time: '2026-09-21 22:15 UTC', title: 'Spatio-Temporal AIS Back-Projection', desc: 'Historical AIS tracks within 6-hour drift window intersected.' },
      { time: '2026-09-21 22:30 UTC', title: 'Candidate Vessel Association Flagged', desc: 'Crude oil tanker PACIFIC ODYSSEY ranked as primary candidate (88% correlation).' },
    ],
    notes: [
      { author: 'Surveillance Officer Rao', date: '2026-09-21 22:45 UTC', text: 'Maritime Coast Guard regional coordination notified. Weather reports indicate calm sea state (Beaufort 2).' },
    ]
  },
  {
    id: 'OS-2026-088',
    timestamp: '2026-09-21T14:12:00Z',
    lat: 18.820,
    lng: 71.450,
    locationName: 'Arabian Sea - Off Gujarat Coast',
    area: 18.4,
    perimeter: 22.6,
    confidence: 91,
    status: 'Active',
    satelliteSource: 'Sentinel-1A (SAR C-Band)',
    driftDirection: 'Southeast (135°)',
    driftSpeed: 1.8,
    description: 'Elongated linear slick pattern consistent with bilge/sludge discharge during vessel transit.',
    candidateVesselsCount: 2,
    timeline: [
      { time: '2026-09-21 14:12 UTC', title: 'SAR Acquisition Complete', desc: 'Level-1 GRD SAR data processed.' },
      { time: '2026-09-21 14:30 UTC', title: 'Anomaly Detected', desc: 'Slick perimeter calculated at 22.6 km.' },
      { time: '2026-09-21 14:55 UTC', title: 'Correlation Run', desc: 'Bulk carrier OCEAN TRADER identified within 3.8 nm of origin.' },
    ],
    notes: [
      { author: 'Cmdr. Patil', date: '2026-09-21 15:10 UTC', text: 'Cross-checked with environmental baseline database. Oil thickness estimated at 0.1-0.5 micrometers.' }
    ]
  },
  {
    id: 'OS-2026-087',
    timestamp: '2026-09-20T19:20:00Z',
    lat: 19.880,
    lng: 69.850,
    locationName: 'Arabian Sea - International Transit Corridor',
    area: 9.6,
    perimeter: 12.1,
    confidence: 86,
    status: 'Under Review',
    satelliteSource: 'Sentinel-2B (MSI Multi-Spectral Optical)',
    driftDirection: 'North-Northwest (330°)',
    driftSpeed: 0.9,
    description: 'Optical multi-spectral reflectance anomaly verified under low cloud-cover conditions.',
    candidateVesselsCount: 2,
    timeline: [
      { time: '2026-09-20 19:20 UTC', title: 'MSI Optical Capture', desc: 'Band 8/4 ratio anomaly detected.' },
      { time: '2026-09-20 20:05 UTC', title: 'Analyst Review Assigned', desc: 'Flagged for false-positive screening (algal bloom check passed).' }
    ],
    notes: []
  },
  {
    id: 'OS-2026-084',
    timestamp: '2026-09-19T08:05:00Z',
    lat: 20.450,
    lng: 71.120,
    locationName: 'Gulf of Khambhat Approaches',
    area: 5.2,
    perimeter: 8.4,
    confidence: 79,
    status: 'Resolved',
    satelliteSource: 'Sentinel-1B (SAR C-Band)',
    driftDirection: 'South (180°)',
    driftSpeed: 2.1,
    description: 'Natural biogenic film patch or weathered slick. Dispersed naturally after 24 hours under tidal turbulence.',
    candidateVesselsCount: 0,
    timeline: [
      { time: '2026-09-19 08:05 UTC', title: 'Initial Flag', desc: 'Low-intensity backscatter contrast registered.' },
      { time: '2026-09-20 12:00 UTC', title: 'Resolution Confirmed', desc: 'No persistent petroleum residue detected in subsequent pass.' }
    ],
    notes: [
      { author: 'Analyst K. Nair', date: '2026-09-20 12:30 UTC', text: 'Confirmed dissipation by regional aerial patrol.' }
    ]
  },
  {
    id: 'OS-2026-082',
    timestamp: '2026-09-18T03:30:00Z',
    lat: 18.150,
    lng: 72.100,
    locationName: 'Off South Konkan Coast',
    area: 21.3,
    perimeter: 28.5,
    confidence: 96,
    status: 'Resolved',
    satelliteSource: 'Sentinel-1A (SAR C-Band)',
    driftDirection: 'East (090°)',
    driftSpeed: 1.2,
    description: 'Major heavy fuel oil release reported and contained by regional response vessels.',
    candidateVesselsCount: 1,
    timeline: [
      { time: '2026-09-18 03:30 UTC', title: 'Detection', desc: 'Severe anomaly flagged.' },
      { time: '2026-09-18 06:00 UTC', title: 'Containment Deployed', desc: 'Boom skimmers deployed.' }
    ],
    notes: []
  },
  {
    id: 'OS-2026-080',
    timestamp: '2026-09-17T16:45:00Z',
    lat: 19.600,
    lng: 70.300,
    locationName: 'Central Arabian Sea Basin',
    area: 7.1,
    perimeter: 9.8,
    confidence: 83,
    status: 'Under Review',
    satelliteSource: 'Sentinel-1B (SAR C-Band)',
    driftDirection: 'Northeast (045°)',
    driftSpeed: 1.5,
    description: 'Moderate backscatter reduction slick detected along south-bound shipping channel.',
    candidateVesselsCount: 1,
    timeline: [
      { time: '2026-09-17 16:45 UTC', title: 'Detection', desc: 'SAR dark spot segmentation output generated.' }
    ],
    notes: []
  }
];

export const DEMO_VESSELS = [
  {
    id: 'VES-01',
    name: 'PACIFIC ODYSSEY',
    mmsi: '538008124',
    imo: '9412354',
    type: 'Crude Oil Tanker',
    flag: 'Marshall Islands',
    lat: 19.380,
    lng: 70.860,
    heading: 68,
    speed: 13.2,
    destination: 'Vadinar Port',
    eta: '2026-09-23 04:00 UTC',
    loa: 274,
    beam: 48,
    lastUpdate: '2026-09-21T22:40:00Z',
    associationStatus: 'Candidate Vessel',
    relatedIncidentId: 'OS-2026-089',
    distanceFromIncident: 4.2,
    correlationScore: 88,
  },
  {
    id: 'VES-02',
    name: 'OCEAN TRADER',
    mmsi: '354921000',
    imo: '9304891',
    type: 'Bulk Carrier',
    flag: 'Panama',
    lat: 18.860,
    lng: 71.490,
    heading: 142,
    speed: 11.5,
    destination: 'Mormugao',
    eta: '2026-09-22 18:00 UTC',
    loa: 225,
    beam: 32,
    lastUpdate: '2026-09-21T22:38:00Z',
    associationStatus: 'Candidate Vessel',
    relatedIncidentId: 'OS-2026-088',
    distanceFromIncident: 3.8,
    correlationScore: 84,
  },
  {
    id: 'VES-03',
    name: 'AL ZUBARAH STAR',
    mmsi: '466023000',
    imo: '9782143',
    type: 'LNG Tanker',
    flag: 'Qatar',
    lat: 19.420,
    lng: 70.780,
    heading: 75,
    speed: 16.8,
    destination: 'Dahej Terminal',
    eta: '2026-09-22 14:00 UTC',
    loa: 299,
    beam: 46,
    lastUpdate: '2026-09-21T22:42:00Z',
    associationStatus: 'Candidate Vessel',
    relatedIncidentId: 'OS-2026-089',
    distanceFromIncident: 8.5,
    correlationScore: 61,
  },
  {
    id: 'VES-04',
    name: 'MSC AURORA V',
    mmsi: '636018240',
    imo: '9845112',
    type: 'Container Ship',
    flag: 'Liberia',
    lat: 19.120,
    lng: 71.150,
    heading: 250,
    speed: 19.4,
    destination: 'Jebel Ali',
    eta: '2026-09-24 09:00 UTC',
    loa: 366,
    beam: 51,
    lastUpdate: '2026-09-21T22:35:00Z',
    associationStatus: 'Monitored',
    relatedIncidentId: null,
    distanceFromIncident: 16.1,
    correlationScore: 28,
  },
  {
    id: 'VES-05',
    name: 'BHARAT SAMUDRA',
    mmsi: '419001429',
    imo: '9621458',
    type: 'Crude Oil Tanker',
    flag: 'India',
    lat: 18.790,
    lng: 71.380,
    heading: 130,
    speed: 12.0,
    destination: 'Kochi Port',
    eta: '2026-09-23 21:00 UTC',
    loa: 250,
    beam: 44,
    lastUpdate: '2026-09-21T22:41:00Z',
    associationStatus: 'Candidate Vessel',
    relatedIncidentId: 'OS-2026-088',
    distanceFromIncident: 5.9,
    correlationScore: 72,
  },
  {
    id: 'VES-06',
    name: 'NORDIC BREEZE',
    mmsi: '257041000',
    imo: '9517208',
    type: 'Chemical Tanker',
    flag: 'Norway',
    lat: 19.280,
    lng: 71.050,
    heading: 70,
    speed: 12.8,
    destination: 'Mumbai Nhava Sheva',
    eta: '2026-09-22 11:30 UTC',
    loa: 182,
    beam: 27,
    lastUpdate: '2026-09-21T22:39:00Z',
    associationStatus: 'Candidate Vessel',
    relatedIncidentId: 'OS-2026-089',
    distanceFromIncident: 9.1,
    correlationScore: 54,
  },
  {
    id: 'VES-07',
    name: 'EVER FORTUNE',
    mmsi: '563098210',
    imo: '9893421',
    type: 'Container Ship',
    flag: 'Singapore',
    lat: 19.920,
    lng: 69.780,
    heading: 320,
    speed: 18.1,
    destination: 'Suez Canal',
    eta: '2026-09-27 12:00 UTC',
    loa: 400,
    beam: 59,
    lastUpdate: '2026-09-21T22:44:00Z',
    associationStatus: 'Candidate Vessel',
    relatedIncidentId: 'OS-2026-087',
    distanceFromIncident: 4.8,
    correlationScore: 77,
  },
  {
    id: 'VES-08',
    name: 'SINDHU SAGAR',
    mmsi: '419098741',
    imo: '9456782',
    type: 'Offshore Support Vessel',
    flag: 'India',
    lat: 19.450,
    lng: 71.250,
    heading: 45,
    speed: 9.2,
    destination: 'Mumbai High Platform North',
    eta: '2026-09-22 06:00 UTC',
    loa: 78,
    beam: 16,
    lastUpdate: '2026-09-21T22:30:00Z',
    associationStatus: 'Monitored',
    relatedIncidentId: null,
    distanceFromIncident: 18.5,
    correlationScore: 19,
  },
  {
    id: 'VES-09',
    name: 'GULF EXPLORER',
    mmsi: '470123999',
    imo: '9312984',
    type: 'Products Tanker',
    flag: 'UAE',
    lat: 19.820,
    lng: 69.940,
    heading: 335,
    speed: 13.6,
    destination: 'Fujairah Anchorage',
    eta: '2026-09-24 16:00 UTC',
    loa: 183,
    beam: 32,
    lastUpdate: '2026-09-21T22:25:00Z',
    associationStatus: 'Candidate Vessel',
    relatedIncidentId: 'OS-2026-087',
    distanceFromIncident: 6.2,
    correlationScore: 68,
  },
  {
    id: 'VES-10',
    name: 'MAERSK KALAMATA',
    mmsi: '219014522',
    imo: '9244946',
    type: 'Container Ship',
    flag: 'Denmark',
    lat: 18.400,
    lng: 71.800,
    heading: 160,
    speed: 17.5,
    destination: 'Colombo',
    eta: '2026-09-23 10:00 UTC',
    loa: 300,
    beam: 40,
    lastUpdate: '2026-09-21T22:33:00Z',
    associationStatus: 'Clear',
    relatedIncidentId: null,
    distanceFromIncident: 34.0,
    correlationScore: 8,
  },
];

export const DEMO_CORRELATIONS = {
  'OS-2026-089': [
    {
      vesselId: 'VES-01',
      vesselName: 'PACIFIC ODYSSEY',
      mmsi: '538008124',
      vesselType: 'Crude Oil Tanker',
      flag: 'Marshall Islands',
      distanceNm: 4.2,
      timeDiffHours: 1.2,
      speedAtWindow: '13.4 kn',
      driftVectorAlignment: 'High (89%)',
      correlationScore: 88,
      associationStatus: 'High Association',
      notes: 'Passed through spill origin point 72 minutes prior to Sentinel-1B radar acquisition.',
    },
    {
      vesselId: 'VES-03',
      vesselName: 'AL ZUBARAH STAR',
      mmsi: '466023000',
      vesselType: 'LNG Tanker',
      flag: 'Qatar',
      distanceNm: 8.5,
      timeDiffHours: 2.1,
      speedAtWindow: '16.8 kn',
      driftVectorAlignment: 'Moderate (64%)',
      correlationScore: 61,
      associationStatus: 'Moderate Association',
      notes: 'Course was parallel to slick axis at distance of 8.5 nm.',
    },
    {
      vesselId: 'VES-06',
      vesselName: 'NORDIC BREEZE',
      mmsi: '257041000',
      vesselType: 'Chemical Tanker',
      flag: 'Norway',
      distanceNm: 9.1,
      timeDiffHours: 2.8,
      speedAtWindow: '12.8 kn',
      driftVectorAlignment: 'Low-Moderate (52%)',
      correlationScore: 54,
      associationStatus: 'Under Assessment',
      notes: 'Within 6-hour drift projection cone. Secondary candidate.',
    },
  ],
  'OS-2026-088': [
    {
      vesselId: 'VES-02',
      vesselName: 'OCEAN TRADER',
      mmsi: '354921000',
      vesselType: 'Bulk Carrier',
      flag: 'Panama',
      distanceNm: 3.8,
      timeDiffHours: 0.9,
      speedAtWindow: '11.5 kn',
      driftVectorAlignment: 'High (92%)',
      correlationScore: 84,
      associationStatus: 'High Association',
      notes: 'Direct transit trajectory alignment with linear slick geometry.',
    },
    {
      vesselId: 'VES-05',
      vesselName: 'BHARAT SAMUDRA',
      mmsi: '419001429',
      vesselType: 'Crude Oil Tanker',
      flag: 'India',
      distanceNm: 5.9,
      timeDiffHours: 1.8,
      speedAtWindow: '12.0 kn',
      driftVectorAlignment: 'Moderate (74%)',
      correlationScore: 72,
      associationStatus: 'Moderate Association',
      notes: 'Trailing track detected in sector.',
    },
  ],
  'OS-2026-087': [
    {
      vesselId: 'VES-07',
      vesselName: 'EVER FORTUNE',
      mmsi: '563098210',
      vesselType: 'Container Ship',
      flag: 'Singapore',
      distanceNm: 4.8,
      timeDiffHours: 1.5,
      speedAtWindow: '18.1 kn',
      driftVectorAlignment: 'Moderate (79%)',
      correlationScore: 77,
      associationStatus: 'Moderate Association',
      notes: 'Optical cross-validation candidate.',
    },
    {
      vesselId: 'VES-09',
      vesselName: 'GULF EXPLORER',
      mmsi: '470123999',
      vesselType: 'Products Tanker',
      flag: 'UAE',
      distanceNm: 6.2,
      timeDiffHours: 2.2,
      speedAtWindow: '13.6 kn',
      driftVectorAlignment: 'Moderate (68%)',
      correlationScore: 68,
      associationStatus: 'Under Assessment',
      notes: 'Upwind corridor transit.',
    }
  ]
};

export const DEMO_ANALYTICS = {
  detectionsOverTime: [
    { date: '15 Sep', incidents: 1, area: 4.2 },
    { date: '16 Sep', incidents: 2, area: 11.5 },
    { date: '17 Sep', incidents: 1, area: 7.1 },
    { date: '18 Sep', incidents: 3, area: 26.8 },
    { date: '19 Sep', incidents: 2, area: 9.4 },
    { date: '20 Sep', incidents: 2, area: 16.3 },
    { date: '21 Sep', incidents: 3, area: 42.8 },
  ],
  areaDistribution: [
    { range: '< 5 km²', count: 8, label: 'Minor (<5 km²)' },
    { range: '5 - 10 km²', count: 14, label: 'Small (5-10 km²)' },
    { range: '10 - 20 km²', count: 9, label: 'Moderate (10-20 km²)' },
    { range: '20 - 50 km²', count: 4, label: 'Large (20-50 km²)' },
    { range: '> 50 km²', count: 1, label: 'Severe (>50 km²)' },
  ],
  correlationDistribution: [
    { bracket: '90-100%', candidates: 3, label: 'Very High Confidence' },
    { bracket: '80-89%', candidates: 6, label: 'High Confidence' },
    { bracket: '70-79%', candidates: 9, label: 'Moderate Confidence' },
    { bracket: '50-69%', candidates: 12, label: 'Low/Indeterminate' },
    { bracket: '< 50%', candidates: 24, label: 'Uncorrelated' },
  ],
  vesselTypes: [
    { name: 'Crude Oil Tankers', count: 48, fill: '#EF4444' },
    { name: 'Chemical Tankers', count: 32, fill: '#F59E0B' },
    { name: 'Container Ships', count: 38, fill: '#3B82F6' },
    { name: 'Bulk Carriers', count: 22, fill: '#22D3EE' },
    { name: 'Offshore & Support', count: 8, fill: '#10B981' },
  ],
};
