import React from 'react';
import {
  Shield,
  Satellite,
  Ship,
  Compass,
  Wind,
  Code2,
  AlertTriangle,
  CheckCircle,
  ExternalLink,
  Cpu,
} from 'lucide-react';

export default function About() {
  return (
    <div className="space-y-6 max-w-4xl">
      {/* Page Title */}
      <div>
        <div className="flex items-center gap-2 mb-1">
          <Shield className="w-4 h-4 text-ocean-cyan" />
          <span className="text-xs font-mono uppercase text-ocean-cyan font-semibold tracking-wider">
            System Mission & Overview
          </span>
        </div>
        <h1 className="text-2xl lg:text-3xl font-bold tracking-tight text-ocean-textPrimary font-sans">
          About OceanShield AI
        </h1>
        <p className="text-xs text-ocean-textSecondary mt-0.5">
          Satellite-driven maritime anomaly detection and automated vessel correlation engine.
        </p>
      </div>

      {/* Mandatory Legal Disclaimer Banner */}
      <div className="p-4 rounded-xl bg-ocean-danger/10 border border-ocean-danger/30 flex items-start gap-3">
        <AlertTriangle className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <h4 className="text-xs font-bold uppercase font-mono text-red-400">
            Operational & Legal Responsibility Notice
          </h4>
          <p className="text-xs text-ocean-textPrimary font-medium">
            “Correlation scores indicate potential associations and do not establish legal responsibility.”
          </p>
          <p className="text-[11px] text-ocean-textSecondary">
            All vessel correlations generated by OceanShield AI are probabilistic geospatial and temporal models derived from AIS transponder reports and satellite image timestamps. They serve as investigative leads for maritime authorities and do not constitute legal proof of fault.
          </p>
        </div>
      </div>

      {/* Core Platform Capabilities */}
      <div className="p-5 rounded-xl bg-ocean-card border border-ocean-border shadow-card space-y-4">
        <h3 className="text-sm font-semibold text-ocean-textPrimary border-b border-ocean-border pb-2">
          Platform Architecture & Capabilities
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="p-4 rounded-lg bg-ocean-secondary border border-ocean-border/60 space-y-1.5">
            <div className="flex items-center gap-2 text-ocean-cyan font-semibold">
              <Satellite className="w-4 h-4" />
              <span>Satellite-Based Oil-Spill Detection</span>
            </div>
            <p className="text-ocean-textSecondary leading-relaxed">
              Leverages Synthetic Aperture Radar (SAR) from Sentinel-1 constellations. SAR penetrates cloud cover and darkness to identify dampening of capillary ocean waves caused by surface hydrocarbons.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-ocean-secondary border border-ocean-border/60 space-y-1.5">
            <div className="flex items-center gap-2 text-ocean-cyan font-semibold">
              <Ship className="w-4 h-4" />
              <span>Maritime Vessel Correlation</span>
            </div>
            <p className="text-ocean-textSecondary leading-relaxed">
              Performs spatio-temporal back-projection on historical AIS broadcasts to identify candidate vessels that crossed the anomaly area within the calculated discharge time window.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-ocean-secondary border border-ocean-border/60 space-y-1.5">
            <div className="flex items-center gap-2 text-ocean-cyan font-semibold">
              <Compass className="w-4 h-4" />
              <span>Geospatial Command Center</span>
            </div>
            <p className="text-ocean-textSecondary leading-relaxed">
              Provides real-time interactive vector mapping, slick perimeter approximations, distance metrics, and automated alert escalation workflows for watch officers.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-ocean-secondary border border-ocean-border/60 space-y-1.5">
            <div className="flex items-center gap-2 text-ocean-cyan font-semibold">
              <Wind className="w-4 h-4" />
              <span>Future Drift Prediction Capabilities</span>
            </div>
            <p className="text-ocean-textSecondary leading-relaxed">
              Integrating hydrodynamic ocean surface current models and Copernicus marine wind vectors to forecast slick dispersion, shoreline impact, and weathering decay.
            </p>
          </div>
        </div>
      </div>

      {/* Technology Stack Grid */}
      <div className="p-5 rounded-xl bg-ocean-card border border-ocean-border shadow-card space-y-3">
        <div className="flex items-center gap-2 pb-2 border-b border-ocean-border">
          <Code2 className="w-4 h-4 text-ocean-cyan" />
          <h3 className="text-sm font-semibold text-ocean-textPrimary">
            Technology Stack
          </h3>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs font-mono">
          <div className="p-2.5 rounded-lg bg-ocean-secondary border border-ocean-border">
            <span className="text-ocean-cyan block font-bold">React 19 + Vite</span>
            <span className="text-[10px] text-ocean-textMuted">High-Performance SPA</span>
          </div>
          <div className="p-2.5 rounded-lg bg-ocean-secondary border border-ocean-border">
            <span className="text-ocean-cyan block font-bold">Tailwind CSS</span>
            <span className="text-[10px] text-ocean-textMuted">Custom Maritime Theme</span>
          </div>
          <div className="p-2.5 rounded-lg bg-ocean-secondary border border-ocean-border">
            <span className="text-ocean-cyan block font-bold">Leaflet & CartoDB</span>
            <span className="text-[10px] text-ocean-textMuted">Dark Tile GIS Mapping</span>
          </div>
          <div className="p-2.5 rounded-lg bg-ocean-secondary border border-ocean-border">
            <span className="text-ocean-cyan block font-bold">Recharts</span>
            <span className="text-[10px] text-ocean-textMuted">Vector Analytics</span>
          </div>
          <div className="p-2.5 rounded-lg bg-ocean-secondary border border-ocean-border">
            <span className="text-ocean-cyan block font-bold">Lucide React</span>
            <span className="text-[10px] text-ocean-textMuted">Tactical Icons</span>
          </div>
          <div className="p-2.5 rounded-lg bg-ocean-secondary border border-ocean-border">
            <span className="text-ocean-cyan block font-bold">Axios Service</span>
            <span className="text-[10px] text-ocean-textMuted">FastAPI Integration Ready</span>
          </div>
        </div>
      </div>

      {/* System Specifications */}
      <div className="p-4 rounded-xl bg-ocean-secondary/70 border border-ocean-border flex flex-col sm:flex-row sm:items-center justify-between text-xs text-ocean-textMuted font-mono gap-2">
        <span>OceanShield AI Client • Build v1.0.0-PROD</span>
        <span>Target Sector: Western Indian Ocean & Arabian Sea</span>
      </div>
    </div>
  );
}
