import React, { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import {
  ArrowLeft,
  AlertOctagon,
  Calendar,
  Compass,
  Satellite,
  Layers,
  Image as ImageIcon,
  FileText,
  Send,
  Download,
  Share2,
  Wind,
  Waves,
  ShieldAlert,
} from 'lucide-react';
import Badge from '../components/common/Badge';
import Button from '../components/common/Button';
import LoadingState from '../components/common/LoadingState';
import ErrorState from '../components/common/ErrorState';
import MaritimeMap from '../components/dashboard/MaritimeMap';
import CandidateVessels from '../components/dashboard/CandidateVessels';
import InvestigationTimeline from '../components/incidents/InvestigationTimeline';
import { useSpill } from '../hooks/useSpills';
import { useCorrelations } from '../hooks/useCorrelations';
import { useVessels } from '../hooks/useVessels';
import { formatCoordinates, formatArea, formatDate } from '../utils/formatters';

export default function IncidentDetails() {
  const { id } = useParams();
  const { spill, loading, error, refetch } = useSpill(id);
  const { correlations } = useCorrelations(id);
  const { vessels } = useVessels();

  const [notes, setNotes] = useState([
    {
      author: 'Surveillance Officer Rao',
      date: '2026-09-21 22:45 UTC',
      text: 'Maritime Coast Guard regional coordination notified. Weather reports indicate calm sea state (Beaufort 2).',
    },
  ]);
  const [newNote, setNewNote] = useState('');
  const [activeEvidenceTab, setActiveEvidenceTab] = useState('raw'); // 'raw' or 'mask'

  const handleAddNote = (e) => {
    e.preventDefault();
    if (!newNote.trim()) return;
    setNotes([
      ...notes,
      {
        author: 'Cmdr. Patil (Watch)',
        date: new Date().toISOString().replace('T', ' ').substring(0, 16) + ' UTC',
        text: newNote.trim(),
      },
    ]);
    setNewNote('');
  };

  if (loading) {
    return <LoadingState message={`Accessing Incident Record ${id}...`} />;
  }

  if (error || !spill) {
    return (
      <div className="space-y-4">
        <Link to="/incidents">
          <Button variant="secondary" size="sm" icon={ArrowLeft}>
            Back to Registry
          </Button>
        </Link>
        <ErrorState
          title="Incident Dossier Not Found"
          message={error || `Incident ID ${id} was not found in the surveillance database.`}
          onRetry={refetch}
        />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Top Navigation & Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Link to="/incidents">
            <button className="p-2 rounded-lg bg-ocean-card hover:bg-ocean-cardHover border border-ocean-border text-ocean-textSecondary hover:text-ocean-textPrimary transition-colors">
              <ArrowLeft className="w-4 h-4" />
            </button>
          </Link>
          <div>
            <div className="flex items-center gap-2 mb-0.5">
              <span className="text-xs font-mono uppercase text-ocean-cyan font-bold tracking-wider">
                DOSSIER • INVESTIGATION
              </span>
              <Badge status={spill.status} />
            </div>
            <h1 className="text-2xl lg:text-3xl font-bold font-mono text-ocean-textPrimary flex items-center gap-2">
              <AlertOctagon className="w-6 h-6 text-red-400" />
              {spill.id}
            </h1>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="secondary"
            size="sm"
            icon={Download}
            onClick={() => alert('PDF export dossier will be generated by the backend.')}
          >
            Export Dossier
          </Button>
          <Button
            variant="outline"
            size="sm"
            icon={Share2}
            onClick={() => alert('Copied incident share link.')}
          >
            Share
          </Button>
        </div>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="p-4 rounded-xl bg-ocean-card border border-ocean-border">
          <span className="text-[10px] font-mono uppercase text-ocean-textMuted block mb-1">
            Estimated Area
          </span>
          <span className="text-xl lg:text-2xl font-bold font-mono text-red-400">
            {formatArea(spill.area)}
          </span>
          <span className="text-[11px] text-ocean-textMuted block mt-0.5">
            Perimeter: ~{spill.perimeter || (spill.area * 1.3).toFixed(1)} km
          </span>
        </div>

        <div className="p-4 rounded-xl bg-ocean-card border border-ocean-border">
          <span className="text-[10px] font-mono uppercase text-ocean-textMuted block mb-1">
            AI Classification Confidence
          </span>
          <span className="text-xl lg:text-2xl font-bold font-mono text-ocean-cyan">
            {spill.confidence}%
          </span>
          <span className="text-[11px] text-ocean-green block mt-0.5">
            High-Backscatter Oil
          </span>
        </div>

        <div className="p-4 rounded-xl bg-ocean-card border border-ocean-border">
          <span className="text-[10px] font-mono uppercase text-ocean-textMuted block mb-1">
            Satellite Source
          </span>
          <span className="text-sm font-bold text-ocean-textPrimary block truncate" title={spill.satelliteSource}>
            {spill.satelliteSource?.split('(')[0]}
          </span>
          <span className="text-[11px] text-ocean-textMuted font-mono block mt-0.5 truncate">
            C-Band SAR Polarimetric
          </span>
        </div>

        <div className="p-4 rounded-xl bg-ocean-card border border-ocean-border">
          <span className="text-[10px] font-mono uppercase text-ocean-textMuted block mb-1">
            Drift Trajectory Model
          </span>
          <span className="text-sm font-bold text-amber-400 block font-mono">
            {spill.driftDirection || 'East-Northeast'}
          </span>
          <span className="text-[11px] text-ocean-textMuted font-mono block mt-0.5">
            Est. drift: {spill.driftSpeed || '1.4'} kn
          </span>
        </div>
      </div>

      {/* Incident Map & Satellite Evidence Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Incident Focused Map */}
        <div className="p-5 rounded-xl bg-ocean-card border border-ocean-border shadow-card flex flex-col justify-between">
          <div className="flex items-center justify-between mb-3 pb-2 border-b border-ocean-border">
            <div className="flex items-center gap-2">
              <Compass className="w-4 h-4 text-ocean-cyan" />
              <h3 className="text-sm font-semibold text-ocean-textPrimary">
                Incident Geospatial Map
              </h3>
            </div>
            <span className="text-xs font-mono text-ocean-textMuted">
              {formatCoordinates(spill.lat, spill.lng)}
            </span>
          </div>

          <MaritimeMap
            spills={[spill]}
            vessels={vessels}
            selectedSpill={spill}
            center={[spill.lat, spill.lng]}
            zoom={9}
            height="360px"
            showLegend={false}
          />
        </div>

        {/* Satellite Imagery & Mask Evidence Placeholders */}
        <div className="p-5 rounded-xl bg-ocean-card border border-ocean-border shadow-card flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-3 pb-2 border-b border-ocean-border">
              <div className="flex items-center gap-2">
                <Satellite className="w-4 h-4 text-ocean-cyan" />
                <h3 className="text-sm font-semibold text-ocean-textPrimary">
                  Satellite Imagery & AI Mask
                </h3>
              </div>

              {/* Tab Selector */}
              <div className="flex items-center gap-1 p-0.5 rounded-lg bg-ocean-secondary border border-ocean-border">
                <button
                  onClick={() => setActiveEvidenceTab('raw')}
                  className={`px-2.5 py-1 text-xs font-mono rounded-md transition-colors ${
                    activeEvidenceTab === 'raw'
                      ? 'bg-ocean-cyan/20 text-ocean-cyan border border-ocean-cyan/40'
                      : 'text-ocean-textSecondary hover:text-ocean-textPrimary'
                  }`}
                >
                  Raw SAR
                </button>
                <button
                  onClick={() => setActiveEvidenceTab('mask')}
                  className={`px-2.5 py-1 text-xs font-mono rounded-md transition-colors ${
                    activeEvidenceTab === 'mask'
                      ? 'bg-ocean-cyan/20 text-ocean-cyan border border-ocean-cyan/40'
                      : 'text-ocean-textSecondary hover:text-ocean-textPrimary'
                  }`}
                >
                  UNet Mask
                </button>
              </div>
            </div>

            {/* Evidence Placeholder Box */}
            <div className="relative h-[360px] rounded-lg bg-ocean-secondary border border-dashed border-ocean-border flex flex-col items-center justify-center p-6 text-center overflow-hidden radar-grid-bg">
              {/* Decorative scanline overlay */}
              <div className="absolute inset-0 bg-gradient-to-b from-ocean-cyan/5 via-transparent to-ocean-main/60 pointer-events-none" />

              <div className="relative z-10 max-w-sm flex flex-col items-center">
                <div className="w-14 h-14 rounded-full bg-ocean-card border border-ocean-border flex items-center justify-center text-ocean-cyan mb-3 shadow-glow-cyan">
                  <ImageIcon className="w-7 h-7 animate-pulse" />
                </div>
                <h4 className="text-sm font-bold text-ocean-textPrimary mb-1">
                  {activeEvidenceTab === 'raw'
                    ? 'Synthetic Aperture Radar (SAR) Scene'
                    : 'AI Segmentation Mask Inference'}
                </h4>
                <p className="text-xs text-amber-400 font-mono mb-2">
                  Satellite evidence will appear after backend integration.
                </p>
                <p className="text-[11px] text-ocean-textMuted">
                  Optical and SAR Level-1 GRD imagery stream directly from Copernicus Hub via FastAPI pipeline.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Candidate Vessel Correlation Table */}
      <CandidateVessels
        correlations={correlations}
        incidentId={spill.id}
      />

      {/* Timeline & Operator Notes Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Investigation Timeline */}
        <div className="p-5 rounded-xl bg-ocean-card border border-ocean-border shadow-card">
          <div className="flex items-center gap-2 mb-4 pb-2 border-b border-ocean-border">
            <Calendar className="w-4 h-4 text-ocean-cyan" />
            <h3 className="text-sm font-semibold text-ocean-textPrimary">
              Investigation Chronology
            </h3>
          </div>
          <InvestigationTimeline timeline={spill.timeline} />
        </div>

        {/* Operator Notes & Incident Log */}
        <div className="p-5 rounded-xl bg-ocean-card border border-ocean-border shadow-card flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-4 pb-2 border-b border-ocean-border">
              <FileText className="w-4 h-4 text-ocean-cyan" />
              <h3 className="text-sm font-semibold text-ocean-textPrimary">
                Surveillance Logs & Analyst Notes
              </h3>
            </div>

            {/* Existing Notes List */}
            <div className="space-y-3 mb-4 max-h-56 overflow-y-auto pr-1">
              {notes.map((n, idx) => (
                <div key={idx} className="p-3 rounded-lg bg-ocean-secondary border border-ocean-border/60 text-xs">
                  <div className="flex items-center justify-between text-ocean-textMuted font-mono text-[10px] mb-1">
                    <span className="text-ocean-cyan font-bold">{n.author}</span>
                    <span>{n.date}</span>
                  </div>
                  <p className="text-ocean-textSecondary">{n.text}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Add Note Form */}
          <form onSubmit={handleAddNote} className="pt-3 border-t border-ocean-border">
            <div className="flex gap-2">
              <input
                type="text"
                value={newNote}
                onChange={(e) => setNewNote(e.target.value)}
                placeholder="Log observation or action note..."
                className="flex-1 px-3 py-2 rounded-lg bg-ocean-secondary border border-ocean-border text-xs text-ocean-textPrimary placeholder:text-ocean-textMuted focus:outline-none focus:border-ocean-cyan"
              />
              <Button variant="primary" size="sm" icon={Send} type="submit">
                Post
              </Button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
